# Numpy Basics <hr style="border:3x solid #FE1919"></hr>

Data Analyst: Dominic L. Quirido

Department: Electrical Engineering

In [1]:
# imports and packages
import numpy as np

In [2]:
from scipy import stats

# 1D Array

In [29]:
array_1d = np.array([1,2,3])
array_1d

array([1, 2, 3])

# 2D Array

In [3]:
my_array = np.array([
    [1,2,3],
    [4,5,6],
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
my_array.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
np.sum(my_array,axis=0)

array([5, 7, 9])

In [6]:
np.sum(my_array,axis=1)

array([ 6, 15])

# Measures of Central Tendency

In [7]:
fruits = np.array([120, 60, 85, 150 ,200])
fruits

array([120,  60,  85, 150, 200])

In [8]:
fruits_mean = np.mean(fruits)
fruits_mean

np.float64(123.0)

In [9]:
median_fruits = np.median(fruits)
median_fruits

np.float64(120.0)

In [10]:
mode_fruits = stats.mode(fruits)
mode_fruits

ModeResult(mode=np.int64(60), count=np.int64(1))

# Jaguar VS Panther

## Jaguar

In [11]:
jaguar = np.array([10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 10.4, 3, 9.8])
jaguar

array([10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8])

In [12]:
mean_jag = np.mean(jaguar)
mean_jag

np.float64(9.399999999999999)

In [13]:
max_jag = np.max(jaguar)
min_jag = np.min(jaguar)

range_jag = max_jag - min_jag
range_jag

np.float64(8.0)

In [14]:
# Q1
q1_jag = np.percentile(jaguar,25)
q1_jag

np.float64(9.4)

In [15]:
# Q2
q2_jag = np.percentile(jaguar,50)
q2_jag

np.float64(9.8)

In [16]:
# Q3
q3_jag = np.percentile(jaguar,75)
q2_jag

np.float64(9.8)

In [17]:
# IQR
iqr_jag = q3_jag - q1_jag
iqr_jag

np.float64(1.049999999999999)

In [18]:
# sample variance
var_jag = np.var(jaguar,ddof=1)
var_jag

np.float64(4.86)

In [19]:
# sample standard deviation
std_jag = np.std(jaguar)
std_jag

np.float64(2.101947149236112)

## Panther

In [20]:
panther= np.array([10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2, 9.1, 9.1])
panther

array([10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1])

In [21]:
mean_pan = np.mean(panther)
mean_pan

np.float64(10.75)

In [22]:
max_pan = np.max(panther)
min_pan = np.min(panther)

range_pan = max_pan - min_pan
range_pan

np.float64(10.9)

In [23]:
# Q1
q1_pan = np.percentile(panther,25)
q1_pan

np.float64(9.125)

In [24]:
# Q2
q2_pan = np.percentile(panther,55)
q2_pan

np.float64(9.865)

In [25]:
# Q3
q3_pan = np.percentile(panther,75)
q3_pan

np.float64(10.625)

In [26]:
# IQR
iqr_pan = q3_pan - q1_pan
iqr_pan

np.float64(1.5)

In [27]:
# sample variance
var_pan = np.var(panther,ddof=1)
var_pan

np.float64(11.082777777777777)

In [28]:
# sample standard deviation
std_pan = np.std(panther)
std_pan

np.float64(3.1582431825304393)